### PR TITLE
add chat_temperature support

### PR DESCRIPTION
**Pull request by i40west**
I noticed that `chat_temperature` as in the documentation was not yet implemented. This PR adds it.

### CODE REVIEW

**Comment by Robitx** [comment]
Hi @i40west thanks for the PR and reminding me I wanted to add this. :slightly_smiling_face: 

Would you be willing to work on it a little bit more? Or I can merge it and expand on it later.

There is a bunch of model settings people might want to use - `temperature`/`top_p`, `max_tokens`  and so on (https://platform.openai.com/docs/api-reference/chat/create). And they might want different configurations for chat vs text/code editing commands.

So I was thinking that `config.chat_model` and `config.command_model` might be either string (`"gpt-3.5-turbo-16k"`/`"gpt-4"`, ..) or lua map table with options `{model: "gpt-3.5-turbo-16k", temperature: 0.7, ...}`

And there would be a helper function taking the `model`, `model_defaults` (strings/map tables) and `messages` which would crunch it (including the validation) and returned the final payload of M.query.

**Comment by i40west** [comment]
Yes, I was looking at the other settings while I was in there, but I wanted to get temperature in there right away for my own use and I didn't want to leave you a big mess to review

**Comment by Robitx** [comment]
@i40west sorry for my reaction time, I've just got back from work.

Could you try the latest version with `temperature/top_p` support ( https://github.com/Robitx/gp.nvim/commit/a9077c02b50f97ebbd29335ec8e50a70a94d4ff6 ) if it satisfies your needs? :slightly_smiling_face:

**Comment by i40west** [comment]
Oh, cool. (I'm also looking at your code thinking, how did I not know we had `max` and `min`? 😂 I never used Lua before neovim...)

One thing, I'm thinking when using the "headers" in the buffer, it should break out the individual settings rather than using JSON directly.

But yeah, I think we can close this PR.

**Pull request closed without merging**
