### PR TITLE
feat: add a :GpLog command

### PR DESCRIPTION
**Pull request by teto**
that opens up the logfile

### CODE REVIEW

**Comment by Robitx** [comment]
There should be `:GpInspectLog` available as default hook:
https://github.com/Robitx/gp.nvim/blob/2372d5323c6feaa2e9c19f7ccb537c615d878e18/lua/gp/config.lua#L538-L547

**Comment by Robitx** [comment]
Good point on both the rename and need to add to help.

**Comment by teto** [comment]
cool. I can rename InspectLog to Log but not sure how to add help to it ?

**Comment by Robitx** [comment]
Help is build automatically from readme. https://github.com/Robitx/gp.nvim?tab=readme-ov-file#other-commands

**Comment by teto** [comment]
closed in favor of #222

**Pull request closed without merging**
